# -*- coding: utf-8 -*-
"""diseasefinal.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_tT3mZQn8utlKmYZZppR-fZGl22w6dgo
"""

from google.colab import files
files.upload()

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d emmarex/plantdisease
!unzip -q plantdisease.zip

import tensorflow as tf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os, random

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import *

DATASET_PATH = "PlantVillage"

image_paths = []
labels = []

for class_name in os.listdir(DATASET_PATH):
    for img in os.listdir(os.path.join(DATASET_PATH, class_name)):
        image_paths.append(os.path.join(DATASET_PATH, class_name, img))
        labels.append(class_name)

train_paths, val_paths, train_labels, val_labels = train_test_split(
    image_paths, labels,
    test_size=0.2,
    stratify=labels,
    random_state=SEED
)

train_df = pd.DataFrame({"filename": train_paths, "class": train_labels})
val_df   = pd.DataFrame({"filename": val_paths, "class": val_labels})

IMG_SIZE = (224,224)
BATCH_SIZE = 32

train_base = ImageDataGenerator(rescale=1./255).flow_from_dataframe(
    train_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_base = ImageDataGenerator(rescale=1./255).flow_from_dataframe(
    val_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

steps_base = train_base.samples // BATCH_SIZE
val_steps  = val_base.samples // BATCH_SIZE

NUM_CLASSES = len(train_df['class'].unique())

model_cnn = Sequential([
    Input(shape=(224,224,3)),

    Conv2D(32,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(64,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Conv2D(128,(3,3),activation='relu'),
    MaxPooling2D(2,2),

    Flatten(),
    Dense(256,activation='relu'),
    Dropout(0.5),

    Dense(NUM_CLASSES, activation='softmax')
])

model_cnn.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_cnn = model_cnn.fit(
    train_base,
    validation_data=val_base,
    epochs=10,
    steps_per_epoch=steps_base,
    validation_steps=val_steps
)

from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

train_mob = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=25,
    zoom_range=0.2,
    horizontal_flip=True
).flow_from_dataframe(
    train_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_mob = ImageDataGenerator(
    preprocessing_function=preprocess_input
).flow_from_dataframe(
    val_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

from tensorflow.keras.applications import MobileNetV2

base_mob = MobileNetV2(input_shape=(224,224,3),
                       include_top=False,
                       weights='imagenet')

base_mob.trainable = False

x = base_mob.output
x = GlobalAveragePooling2D()(x)
x = Dense(128, activation='relu')(x)
x = Dropout(0.5)(x)

output = Dense(NUM_CLASSES, activation='softmax')(x)

model_mob = Model(inputs=base_mob.input, outputs=output)

model_mob.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_mob = model_mob.fit(
    train_mob,
    validation_data=val_mob,
    epochs=10,
    steps_per_epoch=steps_base,
    validation_steps=val_steps
)

from tensorflow.keras.applications.efficientnet import preprocess_input

train_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=30,
    zoom_range=0.2,
    horizontal_flip=True
).flow_from_dataframe(
    train_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input
).flow_from_dataframe(
    val_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

from tensorflow.keras.applications.efficientnet import preprocess_input

train_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=30,
    zoom_range=0.2,
    horizontal_flip=True
).flow_from_dataframe(
    train_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_eff = ImageDataGenerator(
    preprocessing_function=preprocess_input
).flow_from_dataframe(
    val_df, x_col="filename", y_col="class",
    target_size=IMG_SIZE, batch_size=BATCH_SIZE,
    class_mode='categorical', shuffle=False
)

from tensorflow.keras.applications import EfficientNetB0

base_eff = EfficientNetB0(
    input_shape=(224,224,3),
    include_top=False,
    weights='imagenet'
)

base_eff.trainable = False

x = base_eff.output
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)

output = Dense(NUM_CLASSES, activation='softmax')(x)

model_eff = Model(inputs=base_eff.input, outputs=output)

model_eff.compile(
    optimizer=tf.keras.optimizers.Adam(1e-3),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history_eff = model_eff.fit(
    train_eff,
    validation_data=val_eff,
    epochs=10,
    steps_per_epoch=steps_base,
    validation_steps=val_steps
)

def evaluate(model, data, name):
    data.reset()
    y_pred = np.argmax(model.predict(data), axis=1)
    y_true = data.classes

    print(f"\n{name}")
    print(classification_report(y_true, y_pred))

    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8,6))
    sns.heatmap(cm, cmap='Blues')
    plt.title(name)
    plt.show()

    return classification_report(y_true, y_pred, output_dict=True)

r1 = evaluate(model_cnn, val_base, "Baseline")
r2 = evaluate(model_mob, val_mob, "MobileNet")
r3 = evaluate(model_eff, val_eff, "EfficientNet")

def get_metrics(r):
    return r["accuracy"], r["macro avg"]["f1-score"]

a1,f1 = get_metrics(r1)
a2,f2 = get_metrics(r2)
a3,f3 = get_metrics(r3)

print("\nFINAL RESULTS")
print("Model\tAccuracy\tF1")
print(f"CNN\t{a1:.3f}\t{f1:.3f}")
print(f"MobileNet\t{a2:.3f}\t{f2:.3f}")
print(f"EfficientNet\t{a3:.3f}\t{f3:.3f}")

model_eff.save("final_model.h5")

def classwise_accuracy(model, data, name):
    data.reset()
    y_pred = np.argmax(model.predict(data), axis=1)
    y_true = data.classes

    cm = confusion_matrix(y_true, y_pred)
    class_acc = cm.diagonal() / cm.sum(axis=1)

    classes = list(data.class_indices.keys())

    print(f"\n=== {name} Class-wise Accuracy ===")
    for i, acc in enumerate(class_acc):
        print(f"{classes[i]}: {acc*100:.2f}%")

    return cm, class_acc

cm_cnn, acc_cnn = classwise_accuracy(model_cnn, val_base, "CNN")
cm_mob, acc_mob = classwise_accuracy(model_mob, val_mob, "MobileNet")
cm_eff, acc_eff = classwise_accuracy(model_eff, val_eff, "EfficientNet")

def save_cm(cm, title, filename):
    plt.figure(figsize=(10,8))
    sns.heatmap(cm, cmap='Blues')
    plt.title(title)
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.savefig(filename, dpi=300, bbox_inches='tight')
    plt.show()

save_cm(cm_cnn, "CNN Confusion Matrix", "cnn_cm.png")
save_cm(cm_mob, "MobileNet Confusion Matrix", "mob_cm.png")
save_cm(cm_eff, "EfficientNet Confusion Matrix", "eff_cm.png")

import cv2
from tensorflow.keras.models import Model

def make_gradcam_heatmap(img_array, model, last_conv_layer_name):
    grad_model = Model(
        [model.inputs],
        [model.get_layer(last_conv_layer_name).output, model.output]
    )

    with tf.GradientTape() as tape:
        conv_outputs, predictions = grad_model(img_array)
        pred_index = tf.argmax(predictions[0])
        loss = predictions[:, pred_index]

    grads = tape.gradient(loss, conv_outputs)
    pooled_grads = tf.reduce_mean(grads, axis=(0,1,2))

    conv_outputs = conv_outputs[0]
    heatmap = conv_outputs @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)

    heatmap = np.maximum(heatmap, 0)
    heatmap /= np.max(heatmap)

    return heatmap

last_conv_layer = "top_conv"

from tensorflow.keras.preprocessing import image
import random

indices = random.sample(range(len(val_eff.filepaths)), 5)

for i in indices:
    img_path = val_eff.filepaths[i]

    img = image.load_img(img_path, target_size=(224,224))
    img_array = image.img_to_array(img)
    img_array = np.expand_dims(img_array, axis=0)

    heatmap = make_gradcam_heatmap(img_array, model_eff, last_conv_layer)

    heatmap = cv2.applyColorMap(np.uint8(255*heatmap), cv2.COLORMAP_JET)

    img_orig = np.uint8(img_array[0])
    heatmap = cv2.resize(heatmap, (img_orig.shape[1], img_orig.shape[0]))

    overlay = cv2.addWeighted(img_orig, 0.6, heatmap, 0.4, 0)

    plt.figure(figsize=(5,5))
    plt.imshow(overlay)
    plt.title("Grad-CAM (EfficientNet)")
    plt.axis('off')
    plt.show()

plt.imsave("gradcam_sample.png", overlay)

model_eff.save("final_model.h5")

np.save("cnn_classwise.npy", acc_cnn)
np.save("mob_classwise.npy", acc_mob)
np.save("eff_classwise.npy", acc_eff)

from google.colab import files

files.download("final_model.h5")
files.download("eff_cm.png")
files.download("gradcam_sample.png")

!pip install lime

from lime import lime_image
from skimage.segmentation import mark_boundaries
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

explainer = lime_image.LimeImageExplainer()

# pick 1 image
img_path = val_eff.filepaths[0]

img = image.load_img(img_path, target_size=(224,224))
img_array = image.img_to_array(img)

def predict_fn(images):
    images = images / 255.0
    return model_eff.predict(images)

explanation = explainer.explain_instance(
    img_array.astype('double'),
    predict_fn,
    top_labels=1,
    hide_color=0,
    num_samples=500   # keep low for speed
)

temp, mask = explanation.get_image_and_mask(
    explanation.top_labels[0],
    positive_only=True,
    num_features=5
)

plt.imshow(mark_boundaries(temp, mask))
plt.title("LIME Explanation")
plt.axis('off')
plt.show()

!pip install shap

import shap
import numpy as np
import matplotlib.pyplot as plt

# Take small batch from validation generator
val_eff.reset()
X_batch, _ = next(val_eff)

# Background (for SHAP baseline)
background = X_batch[:20]   # small set

# Test images to explain
test_images = X_batch[20:25]  # 5 images only

explainer = shap.GradientExplainer(model_eff, background)

shap_values = explainer.shap_values(test_images)

shap.image_plot(shap_values, test_images)